default:
	cd makeprocs; make
	cd H2O; make
	cd NO; make
	cd react1; make
	cd react2; make
	cd react3; make

clean:
	cd makeprocs; make clean
	cd H2O; make clean
	cd NO; make clean
	cd react1; make clean
	cd react2; make clean
	cd react3; make clean

run:
	cd ../../bin; dlxsim -x os.dlx.obj -a -u makeprocs.dlx.obj 3 4; ee469_fixterminal
